// Api actions
export const GET_INIT = 'GET_INIT';
export const GET_ONE_INIT = 'GET_ONE_INIT';
export const GET_IN_INIT = 'GET_IN_INIT';
export const GET_GRAPH_INIT = 'GET_GRAPH_INIT';
export const GET_COUNT_INIT = 'GET_COUNT_INIT';
export const LIKE_INIT = 'LIKE_INIT';
export const UNLIKE_INIT = 'UNLIKE_INIT';
export const PUT_INIT = 'PUT_INIT';
export const PATCH_INIT = 'PATCH_INIT';
export const POST_INIT = 'POST_INIT';
export const DELETE_INIT = 'DELETE_INIT';
export const GET_SUCCESS = 'GET_SUCCESS';
export const GET_ONE_SUCCESS = 'GET_ONE_SUCCESS';
export const GET_IN_SUCCESS = 'GET_IN_SUCCESS';
export const GET_GRAPH_SUCCESS = 'GET_GRAPH_SUCCESS';
export const GET_COUNT_SUCCESS = 'GET_COUNT_SUCCESS';
export const LIKE_SUCCESS = 'LIKE_SUCCESS';
export const UNLIKE_SUCCESS = 'UNLIKE_SUCCESS';
export const PUT_SUCCESS = 'PUT_SUCCESS';
export const PATCH_SUCCESS = 'PATCH_SUCCESS';
export const POST_SUCCESS = 'POST_SUCCESS';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const GET_ERROR = 'GET_ERROR';
export const GET_ONE_ERROR = 'GET_ONE_ERROR';
export const GET_IN_ERROR = 'GET_IN_ERROR';
export const GET_GRAPH_ERROR = 'GET_GRAPH_ERROR';
export const GET_COUNT_ERROR = 'GET_COUNT_ERROR';
export const LIKE_ERROR = 'LIKE_ERROR';
export const UNLIKE_ERROR = 'UNLIKE_ERROR';
export const PUT_ERROR = 'PUT_ERROR';
export const PATCH_ERROR = 'PATCH_ERROR';
export const POST_ERROR = 'POST_ERROR';
export const DELETE_ERROR = 'DELETE_ERROR';
export const SIGNIN_INIT = 'SIGNIN_INIT';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNOUT = 'SIGNOUT';
export const GET_LOCATION = 'GET_LOCATION';
export const SIGNUP_INIT = 'SIGNUP_INIT';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const APPEND_TO_FILTER = 'APPEND_TO_FILTER';
export const PREPEND_TO_FILTER = 'PREPEND_TO_FILTER';
export const SET_ATTR_SUCCESS = 'SET_ATTR_SUCCESS';
export const SET_ATTR_ERROR = 'SET_ATTR_ERROR';
export const REMOVE_ATTR_SUCCESS = 'REMOVE_ATTR_SUCCESS';
export const REMOVE_ATTR_ERROR = 'REMOVE_ATTR_ERROR';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const GET_POPULAR_CITIES = 'GET_POPULAR_CITIES';
export const GET_POPULAR_CITIES_BY_COUNTRY = 'GET_POPULAR_CITIES_BY_COUNTRY';
export const GET_POPULAR_TYPES = 'GET_POPULAR_TYPES';

export const GET_FEED_INIT = 'GET_FEED_INIT';
export const GET_FEED_SUCCESS = 'GET_FEED_SUCCESS';
export const GET_FEED_ERROR = 'GET_FEED_ERROR';
export const GET_PLACE_FEED_INIT = 'GET_PLACE_FEED_INIT';
export const GET_PLACE_FEED_SUCCESS = 'GET_PLACE_FEED_SUCCESS';
export const GET_PLACE_FEED_ERROR = 'GET_PLACE_FEED_ERROR';
export const GET_DISCOVER_INIT = 'GET_DISCOVER_INIT';
export const GET_DISCOVER_SUCCESS = 'GET_DISCOVER_SUCCESS';
export const GET_DISCOVER_ERROR = 'GET_DISCOVER_ERROR';
export const FOLLOW_INIT = 'FOLLOW_INIT';
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const FOLLOW_ERROR = 'FOLLOW_ERROR';
export const UNFOLLOW_INIT = 'UNFOLLOW_INIT';
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS';
export const UNFOLLOW_ERROR = 'UNFOLLOW_ERROR';
export const SEARCH_POSTS_INIT = 'SEARCH_POSTS_INIT';
export const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS';
export const SEARCH_POSTS_ERROR = 'SEARCH_POSTS_ERROR';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const RECOVER_PASSWORD = 'RECOVER_PASSWORD';
export const ADMIN_STATS = 'ADMIN_STATS';

// App actions
export const READY_RENDER = 'READY_RENDER';

// Search
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SEARCH_AUTOCOMPLETE_SUCCESS = 'SEARCH_AUTOCOMPLETE_SUCCESS';
export const SEARCH_AUTOCOMPLETE_ERROR = 'SEARCH_AUTOCOMPLETE_ERROR';

export const FETCH_CITIES_INIT = 'FETCH_CITIES_INIT';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_ERROR = 'FETCH_CITIES_ERROR';
export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS';
export const FETCH_CITY_ERROR = 'FETCH_CITY_ERROR';

export const FETCH_USERS_INIT = 'FETCH_USERS_INIT';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const FETCH_PLACES_INIT = 'FETCH_PLACES_INIT';
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS';
export const FETCH_PLACES_ERROR = 'FETCH_PLACES_ERROR';
export const FETCH_PLACE_SUCCESS = 'FETCH_PLACE_SUCCESS';
export const FETCH_PLACE_ERROR = 'FETCH_PLACE_ERROR';

export const FETCH_CONVERSATIONS_SUCCESS = 'FETCH_CONVERSATIONS_SUCCESS';
export const FETCH_CONVERSATIONS_ERROR = 'FETCH_CONVERSATIONS_ERROR';
export const FETCH_CONVERSATION_SUCCESS = 'FETCH_CONVERSATION_SUCCESS';
export const FETCH_CONVERSATION_ERROR = 'FETCH_CONVERSATION_ERROR';

export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';

export const WINDOW_RESIZE = 'WINDOW_RESIZE';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const OPEN_CONVERSATION = 'OPEN_CONVERSATION';
export const TOGGLE_ACTIVITY = 'TOGGLE_ACTIVITY';
export const TOGGLE_MOBILE_MENU = 'TOGGLE_MOBILE_MENU';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const TOGGLE_MAP_VIEW = 'TOGGLE_MAP_VIEW';

export const PAGE_CHANGE = 'PAGE_CHANGE';
export const PAGE_ERROR = 'PAGE_ERROR';
export const PAGE_STATUS_CHANGE = 'PAGE_STATUS_CHANGE';
export const PAGE_FORMAT_META = 'PAGE_FORMAT_META';
export const SET_CAMPAIGN = 'SET_CAMPAIGN';

export const KEY_UP = 38;
export const KEY_DOWN = 40;
export const KEY_ENTER = 13;

export const NEWSLETTER_SUBSCRIBE_SUCCESS = 'NEWSLETTER_SUBSCRIBE_SUCCESS';
export const NEWSLETTER_SUBSCRIBE_ERROR = 'NEWSLETTER_SUBSCRIBE_ERROR';

export const FETCH_ADMIN_GRAPH = 'FETCH_ADMIN_GRAPH';
export const FETCH_ADMIN_GRAPH_ERROR = 'FETCH_ADMIN_GRAPH_ERROR';

export const REFUND_PERIODS = {
  MONTH: 30,
  WEEK: 7,
  DAY: 1,
  LASTDAY: 0
}
